server:
  port: ${PORT_CATEGORIZATION_SERVICE:8084}

spring:
  application:
    name: categorization-service
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: categorization-group

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.victorblasco.fintrack.categorization: INFO
    org.springframework.kafka: INFO
